theme: jekyll-theme-minimal
title: Masatoshi Suzuki
description: Graduate student at Tohoku University
links: [{name: GitHub, url: "https://github.com/singletongue"},
        {name: "Inui-Okazaki Lab", url: "http://www.cl.ecei.tohoku.ac.jp"}]
